4Guofeng4XL_v12.safetensors:
  sd_version: ""
  trigger_word: ""
  prompt: "((extremely detailed CG)),((8k_wallpaper)),(masterpiece),best quality,high resolution illustration,hyperdetailed,highres,((Overexposure)),bare shoulders,(Upper body),head tilt,seiza,seductive smile,1girl,long hair,beautiful_face,Highly detailed and beautiful eyes,(an extremely delicate and beautiful),(Beautiful and detailed facial depiction),Mature women Chinese antique clothing,White and blue Taoist robe,earrings,necklace,Winter snow,"
  negative_prompt: "(((simple background))),monochrome,lowres,bad anatomy,bad hands,text,error,missing fingers,extra digit,fewer digits,cropped,worst quality,low quality,normal quality,jpeg artifacts,signature,watermark,username,blurry,lowres,bad anatomy,bad hands,text,error,extra digit,fewer digits,cropped,worst quality,low quality,normal quality,jpeg artifacts,signature,watermark,username,blurry,ugly,pregnant,vore,duplicate,morbid,mut ilated,tran nsexual,hermaphrodite,long neck,mutated hands,poorly drawn hands,poorly drawn face,mutation,deformed,blurry,bad anatomy,bad proportions,malformed limbs,extra limbs,cloned face,disfigured,gross proportions,(((missing arms))),(((missing legs))),(((extra arms))),(((extra legs))),pubic hair,plump,bad legs,error legs,username,blurry,bad feet,"
  cfg: 8.5
  steps: 60
  sampler_name: euler_ancestral
  scheduler: Karras
  clip_skip: 2
  vae_name: ""
  seed: 1312342312
  denoise: ""
abyssorangemix3AOM3_aom3a1b:
  sd_version: ""
  trigger_word: ""
  prompt: "((extremely detailed CG)),((8k_wallpaper)),(masterpiece),best quality,high resolution illustration,hyperdetailed,highres,((Overexposure)),bare shoulders,(Upper body),head tilt,seiza,seductive smile,1girl,long hair,beautiful_face,Highly detailed and beautiful eyes,(an extremely delicate and beautiful),(Beautiful and detailed facial depiction),Mature women Chinese antique clothing,White and blue Taoist robe,earrings,necklace,Winter snow,"
  negative_prompt: "(((simple background))),monochrome,lowres,bad anatomy,bad hands,text,error,missing fingers,extra digit,fewer digits,cropped,worst quality,low quality,normal quality,jpeg artifacts,signature,watermark,username,blurry,lowres,bad anatomy,bad hands,text,error,extra digit,fewer digits,cropped,worst quality,low quality,normal quality,jpeg artifacts,signature,watermark,username,blurry,ugly,pregnant,vore,duplicate,morbid,mut ilated,tran nsexual,hermaphrodite,long neck,mutated hands,poorly drawn hands,poorly drawn face,mutation,deformed,blurry,bad anatomy,bad proportions,malformed limbs,extra limbs,cloned face,disfigured,gross proportions,(((missing arms))),(((missing legs))),(((extra arms))),(((extra legs))),pubic hair,plump,bad legs,error legs,username,blurry,bad feet,"
  cfg: 8.5
  steps: 60
  sampler_name: euler_ancestral
  scheduler: Karras
  clip_skip: 2
  vae_name: ""
  seed: 1312342312
  denoise: ""
"《唯》· 超高清写实重制典藏版 _ OnlyRealistic _v30 典藏版":
  sd_version: ""
  trigger_word: ""
  prompt: "((extremely detailed CG)),((8k_wallpaper)),(masterpiece),best quality,high resolution illustration,hyperdetailed,highres,((Overexposure)),bare shoulders,(Upper body),head tilt,seiza,seductive smile,1girl,long hair,beautiful_face,Highly detailed and beautiful eyes,(an extremely delicate and beautiful),(Beautiful and detailed facial depiction),Mature women Chinese antique clothing,White and blue Taoist robe,earrings,necklace,Winter snow,"
  negative_prompt: "(((simple background))),monochrome,lowres,bad anatomy,bad hands,text,error,missing fingers,extra digit,fewer digits,cropped,worst quality,low quality,normal quality,jpeg artifacts,signature,watermark,username,blurry,lowres,bad anatomy,bad hands,text,error,extra digit,fewer digits,cropped,worst quality,low quality,normal quality,jpeg artifacts,signature,watermark,username,blurry,ugly,pregnant,vore,duplicate,morbid,mut ilated,tran nsexual,hermaphrodite,long neck,mutated hands,poorly drawn hands,poorly drawn face,mutation,deformed,blurry,bad anatomy,bad proportions,malformed limbs,extra limbs,cloned face,disfigured,gross proportions,(((missing arms))),(((missing legs))),(((extra arms))),(((extra legs))),pubic hair,plump,bad legs,error legs,username,blurry,bad feet,"
  cfg: 8.5
  steps: 60
  sampler_name: euler_ancestral
  scheduler: Karras
  clip_skip: 2
  vae_name: ""
  seed: 1312342312
  denoise: ""
another_model.safetensors:
  sd_version: ""
  trigger_word: ""
  prompt: "some prompt here"
  negative_prompt: "some negative prompt here"
  cfg: 7.0
  steps: 30
  sampler_name: dpmpp_2m
  scheduler: karras
  clip_skip: 1
  vae_name: ""
  seed: 0
  denoise: ""